### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by ghost** [shardick/twitch-commando#13]
## Versions
 - **discord.js:** `12.5.1`
 - **node:** `12.0.0`
 - **twitch-commando:** `1.0.12`
 
 ## Operating system
 - **OS:** `Ubuntu 18.04`
 
 ## Description

 I keep getting `TypeError: Cannot read property 'get' of undefined` when the bot tries to connect to Twitch Chat.
 
 ## Console Log
 
 ```json
 0|TwitchBot  | info: Register command system:eval
0|TwitchBot  | info: Register command system:help
0|TwitchBot  | info: Register command system:join
0|TwitchBot  | info: Register command system:part
0|TwitchBot  | info: Register command system:prefix
0|TwitchBot  | info: Loading global emotes
0|TwitchBot  | info: Current default prefix is !
0|TwitchBot  | info: Connecting to Twitch Chat
0|TwitchBot  | TypeError: Cannot read property 'get' of undefined
0|TwitchBot  |     at TwitchCommandoClient.connect (/home/mountaint-dev/TwitchBot/node_modules/twitch-commando/src/client/TwitchCommandoClient.js:133:60)
0|TwitchBot  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 ```

**Comment by dowmeister** [comment]
Is this a thing yet?
